### ISSUE TITLE
broken demo links in documentation

### ISSUE THREAD

**Issue by cyfrmedia** [skypher/cerridwen#11]
Dunno if you're aware of this yet, but I figured I might as well drop in just in case you aren't:
the link to the JSON API demo server's broken, (as are all the other http://cerridwen.viridian-project.de/* links as far as I can tell); seems like the viridian-project.de domain is up for sale.

Best wishes!

**Comment by skypher** [comment]
Should be all fixed. I'd appreciate it if you could double-check. Thanks!

**Comment by cyfrmedia** [comment]
> Should be all fixed. I'd appreciate it if you could double-check. Thanks!

Checked, it's up! Thanks!
